### ISSUE TITLE
Switching from Trendweight.com

### ISSUE THREAD

**Issue by pip8786** [trendweight/trendweight#178]
My wife and I have been using trendweight for 6 years+, thanks for building it, it's awesome. Today I randomly googled trendweight and trendweight.io came up so I had a question:
Is it ready to be used (I see a beta tag on it)? Will logging in with the same credentials as trendweight.com work and have the data ported over?

I'm excited to see you building it on Typescript and Next, that's my preferred tech stack. Hopefully I can contribute some time.

**Comment by ervwalter** [comment]
It's not ready--life got in the way and I haven't made progress in a long time.  

The existing site's code is old and crusty and it's impractical for me to do much new with it.  Fortunately, it is stable and rarely needs attention.  The new site is intended to be the same feature set, just with a manageable codebase.

The new site uses an entirely different backend for authentication and data storage and so it's likely that everyone will need to setup new login credentials as I don't want to attempt to port the username and passwords over from the existing site.  I'd like to create a way that accounts are pre-populated for people and all they have to do is "reset their password" to get into the new site.

The weight data for trendweight.com is only cached in the trendweight database--the real source of truth is aways the fitbit and withings websites.  The new site will end up getting the same data because it will simply retrieve it from the fitbit and withings in the same ways that the old site did.  That part should be nearly seamless to users.

**Comment by pip8786** [comment]
That makes sense, thanks for the response. I wonder if you might want to put a notice on trendweight.io for the time being since it comes up when you google Trendweight as the second hit (at least on my google). 

Speaking to the data, a few times I've had to do the reset of the data to get it fresh from fitbit, and I'm always afraid it's not going to be able to get it all, but seems like you expect fitbit/withings to provide historical data which is good. 

If you have any issues you want me to look at, let me know. I've got a lot of experience in typescript and nextjs. Annoyingly, my time is limited as well, but maybe I can contribute a little bit here and there.

**Comment by pip8786** [comment]
Probably not the best place to ask this, but I saw you removed Turborepo from your project. Any particular reason you didn't like it? I'm using it on a couple projects to manage the monorepo structure and it's been working well for me. I like the fact that it's backed by NextJS now so hopefully that means it won't disappear or lay forgotten.

**Comment by ervwalter** [comment]
Removing it was an experiment because the latest Renovate PR (updated dependencies) isn't building on Vercel.  I thought it might be TurboRepo, so I removed it, but that didn't work, and I just haven't put it back in.  I intend to put it back though.

Nor have I taken the time to update dependencies one at a time to figure out which one causes Vercel to fail with a unhelpful message (seems like it must be Next.js, itself, but I haven't narrowed it down.

**Comment by pip8786** [comment]
Ah I see, thanks for the insight. Alas I can't see the reason it fails since Vercel doesn't put the errors back on Github. Renovate looks interesting, I should look into that for my projects.

**Comment by ervwalter** [comment]
For what it is worth, but build error was a bug in Next.js that they fixed in the latest canary build, so the PR is working now.

Also, since this was more of a question than an issue, I'm going to close it to keep my OCD in check.  I did notice that the discussions feature was not enabled for the project so it's on now in case you or others want to start other discussions.

**Comment by pip8786** [comment]
Sounds good, thanks! Yeah, I wouldn't usually file this as an issue, but figured it might be helpful for anyone to randomly stumble upon it to know. I could add an issue to mention on the homepage of trendweight.io that it's not ready for use, if that's helpful?
